---
# 预检查任务
- name: Check if Nginx service exists
  stat:
    path: /usr/sbin/nginx
  register: nginx_binary
  changed_when: false

- name: Check Nginx service status
  systemd:
    name: nginx
    state: stopped
  ignore_errors: yes
  when: nginx_binary.stat.exists

- name: Install prerequisites
  apt:
    name: 
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
    state: present
    update_cache: yes

- name: Add Nginx signing key
  ansible.builtin.get_url:
    url: https://nginx.org/keys/nginx_signing.key
    dest: /usr/share/keyrings/nginx-archive-keyring.asc
    mode: '0644'

- name: Import Nginx signing key
  ansible.builtin.shell: |
    cat /usr/share/keyrings/nginx-archive-keyring.asc | gpg --dearmor > /usr/share/keyrings/nginx-archive-keyring.gpg

- name: Add Nginx repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx"
    state: present
    filename: nginx
    update_cache: yes

- name: Remove conflicting Nginx packages
  apt:
    name: 
      - nginx-common
      - nginx-core
    state: absent
    purge: yes
  ignore_errors: yes

- name: Install Nginx 1.24
  apt:
    name: nginx=1.24.*
    state: present
    update_cache: yes

- name: Ensure Nginx directories exist with correct permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
  with_items:
    - /etc/nginx
    - /etc/nginx/conf.d
    - /var/log/nginx
    - /usr/share/nginx/html

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart nginx

- name: Configure default site
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart nginx

- name: Create default index.html
  copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Welcome to nginx!</title>
      </head>
      <body>
          <h1>Welcome to nginx on Ubuntu 24.04!</h1>
          <p>If you see this page, the nginx web server is successfully installed and working.</p>
      </body>
      </html>
    dest: /usr/share/nginx/html/index.html
    mode: '0644'
    owner: www-data
    group: www-data

- name: Verify Nginx configuration
  command: nginx -t
  register: nginx_config_test
  changed_when: false

- name: Debug Nginx configuration test
  debug:
    var: nginx_config_test
  when: nginx_config_test.rc != 0

- name: Start and enable Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
  register: nginx_start

- name: Debug Nginx start failure
  block:
    - name: Get Nginx status
      command: systemctl status nginx
      register: nginx_status
      ignore_errors: yes

    - name: Get Nginx logs
      command: journalctl -xeu nginx.service
      register: nginx_logs
      ignore_errors: yes

    - name: Display debug information
      debug:
        msg: 
          - "Nginx Status:"
          - "{{ nginx_status.stdout_lines | default([]) }}"
          - "Nginx Logs:"
          - "{{ nginx_logs.stdout_lines | default([]) }}"
  when: nginx_start.failed is defined and nginx_start.failed 