---
- name: Add Nginx Repository
  block:
    - name: Add Nginx signing key
      ansible.builtin.apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Add Nginx repository
      ansible.builtin.apt_repository:
        repo: "deb http://nginx.org/packages/debian/ bookworm nginx"
        state: present
        filename: nginx

- name: Install Nginx 1.24
  apt:
    name: nginx=1.24.*
    state: present
    update_cache: yes

- name: Start and enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Configure default site
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx 