---
- name: Add Grafana GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Start and enable Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: yes

# 等待 Grafana 启动
- name: Wait for Grafana to start
  wait_for:
    port: 3000
    timeout: 30

# 安装 grafana-cli 工具
- name: Install grafana-cli tools
  apt:
    name: python3-requests
    state: present

# 配置数据源
- name: Configure Prometheus datasource
  uri:
    url: "http://localhost:3000/api/datasources"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    body_format: json
    body:
      name: "Prometheus"
      type: "prometheus"
      url: "http://localhost:9090"
      access: "proxy"
      isDefault: true
    status_code: [200, 409]  # 409 表示数据源已存在
    headers:
      Content-Type: "application/json"

# 导入仪表盘
- name: Import Nginx dashboard
  uri:
    url: "http://localhost:3000/api/dashboards/db"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    body_format: json
    body: "{{ lookup('file', 'templates/nginx-dashboard.json') | from_json | combine({'overwrite': true}) }}"
    status_code: 200
    headers:
      Content-Type: "application/json" 