---
- name: Add Grafana GPG key
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
    filename: grafana

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Start and enable Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: yes

- name: Configure Prometheus datasource
  grafana_datasource:
    name: "Prometheus"
    ds_type: "prometheus"
    ds_url: "http://localhost:9090"
    access: "proxy"
    is_default: yes
    state: present

- name: Import Nginx dashboard
  grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: admin
    grafana_password: admin
    state: present
    overwrite: yes
    path: templates/nginx-dashboard.json 