---
- name: Install Nginx Monitoring
  hosts: nginx
  become: yes
  roles:
    - nginx-exporter
    - role: prometheus
      tags: ['prometheus']
      vars:
        prometheus_targets:
          - name: nginx
            targets:
              - localhost:9113
        prometheus_rules:
          - nginx.rules.yml

- hosts: all
  become: yes
  roles:
    - nginx-exporter  # 安装 Nginx Exporter

  tasks:
    # 添加 Nginx 监控配置到 Prometheus
    - name: Add Nginx scrape config to Prometheus
      blockinfile:
        path: /etc/prometheus/prometheus.yml
        marker: "# {mark} NGINX SCRAPE CONFIG"
        block: |
          - job_name: 'nginx'
            static_configs:
              - targets: ['localhost:9113']
            metrics_path: /metrics
      notify: restart prometheus

    # 添加 Nginx 告警规则
    - name: Add Nginx alert rules
      copy:
        src: roles/prometheus/templates/nginx.rules.yml
        dest: /etc/prometheus/nginx.rules.yml
      notify: restart prometheus

    # 导入 Nginx Grafana 仪表盘
    - name: Import Nginx dashboard to Grafana
      uri:
        url: "http://localhost:3000/api/dashboards/db"
        method: POST
        user: admin
        password: "{{ grafana_admin_password | default('grafana') }}"
        force_basic_auth: yes
        body_format: json
        body:
          dashboard: "{{ lookup('file', 'roles/grafana/templates/dashboards/nginx.json.j2') | from_json }}"
          overwrite: true
          message: "Updated by Ansible"
        status_code: 200
        headers:
          Content-Type: "application/json"

  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted
        daemon_reload: yes 