---
- name: Install Percona Monitoring
  hosts: all
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Create Prometheus rules directory
      file:
        path: /etc/prometheus/rules
        state: directory
        mode: '0755'

    - name: Create MySQL alert rules
      template:
        src: roles/prometheus/templates/mysql.rules.yml.j2
        dest: /etc/prometheus/mysql.rules.yml
        mode: '0644'
      notify: reload prometheus

    - name: Add MySQL rules to Prometheus config
      lineinfile:
        path: /etc/prometheus/prometheus.yml
        insertafter: "rule_files:"
        line: "  - /etc/prometheus/mysql.rules.yml"
      notify: reload prometheus

    - name: Import Grafana MySQL dashboard
      copy:
        src: roles/grafana/templates/dashboards/mysql.json.j2
        dest: /etc/grafana/provisioning/dashboards/mysql.json
        mode: '0644'
      notify: restart grafana

  handlers:
    - name: reload prometheus
      systemd:
        name: prometheus
        state: reloaded

    - name: restart grafana
      systemd:
        name: grafana-server
        state: restarted 