---
- name: Install PHP-FPM Monitoring
  hosts: all
  become: yes
  vars:
    php_default_version: "8.2"  # 设置默认 PHP 版本
    php_available_versions:
      "8.1":
        status_port: 9001
        priority: 10
        state: present
      "8.2":
        status_port: 9002
        priority: 20
        state: present
      "8.3":
        status_port: 9003
        priority: 30
        state: present
      "8.4":
        status_port: 9004
        priority: 40
        state: present

  roles:
    - php-fpm-exporter

  tasks:
    # 添加 PHP-FPM 监控配置到 Prometheus
    - name: Add PHP-FPM scrape config to Prometheus
      blockinfile:
        path: /etc/prometheus/prometheus.yml
        marker: "# {mark} PHP-FPM SCRAPE CONFIG"
        block: |
          - job_name: 'php-fpm'
            static_configs:
              - targets: ['localhost:9253']
      notify: restart prometheus

    # 添加 PHP-FPM 告警规则
    - name: Add PHP-FPM alert rules
      copy:
        src: roles/prometheus/templates/php-fpm.rules.yml
        dest: /etc/prometheus/php-fpm.rules.yml
      notify: restart prometheus

    # 导入 PHP-FPM Grafana 仪表盘
    - name: Import PHP-FPM dashboard to Grafana
      uri:
        url: "http://localhost:3000/api/dashboards/db"
        method: POST
        user: admin
        password: "{{ grafana_admin_password | default('grafana') }}"
        force_basic_auth: yes
        body_format: json
        body:
          dashboard: "{{ lookup('file', 'roles/grafana/templates/dashboards/php-fpm.json.j2') | from_json }}"
          overwrite: true
          message: "Updated by Ansible"
        status_code: 200
        headers:
          Content-Type: "application/json"

  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted
        daemon_reload: yes 