---
- name: Uninstall RabbitMQ
  hosts: all
  become: yes
  tasks:
    - name: Check services
      command: systemctl status {{ item }}
      register: service_check
      failed_when: false
      changed_when: false
      with_items:
        - rabbitmq-server
        - rabbitmq-exporter

    - name: Stop services if they exist
      systemd:
        name: "{{ item.item }}"
        state: stopped
      when: item.rc == 0
      with_items: "{{ service_check.results }}"
      ignore_errors: yes

    - name: Remove packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      with_items:
        - rabbitmq-server
        - erlang
      ignore_errors: yes

    - name: Clean directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/rabbitmq
        - /etc/rabbitmq
        - /var/log/rabbitmq
      ignore_errors: yes

    - name: Remove RabbitMQ user
      user:
        name: rabbitmq
        state: absent
        remove: yes
      ignore_errors: yes

    - name: Remove RabbitMQ group
      group:
        name: rabbitmq
        state: absent
      ignore_errors: yes

    - name: Remove RabbitMQ repository
      apt_repository:
        repo: "deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu {{ ansible_distribution_release }} main"
        state: absent
      ignore_errors: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    # 清理 systemd
    - name: Clean systemd
      command: systemctl daemon-reload

    # 清理日志
    - name: Clean RabbitMQ logs
      command: journalctl --vacuum-time=1s --unit=rabbitmq-server
      ignore_errors: yes

    - name: Clean RabbitMQ Exporter logs
      command: journalctl --vacuum-time=1s --unit=rabbitmq-exporter
      ignore_errors: yes 