---
- name: Uninstall RabbitMQ and clean up
  hosts: all
  become: yes
  tasks:
    # 停止服务
    - name: Stop RabbitMQ services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - rabbitmq-server
        - rabbitmq-exporter
      ignore_errors: yes

    # 删除仓库配置文件
    - name: Remove RabbitMQ repository files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/sources.list.d/rabbitmq.list
        - /etc/apt/sources.list.d/rabbitmq-erlang.list
        - /usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg
        - /usr/share/keyrings/rabbitmq.9F4587F226208342.gpg
        - /usr/share/keyrings/com.rabbitmq.team.gpg
        - /etc/apt/keyrings/rabbitmq.asc
        - /etc/apt/keyrings/rabbitmq.gpg
        - /etc/apt/keyrings/rabbitmq-erlang.asc
        - /etc/apt/keyrings/rabbitmq-erlang.gpg

    # 更新包缓存
    - name: Update package cache
      apt:
        update_cache: yes
      ignore_errors: yes

    # 卸载 RabbitMQ 相关包
    - name: Remove RabbitMQ packages
      apt:
        name:
          - rabbitmq-server
          - erlang*
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes

    # 删除配置文件和数据目录
    - name: Remove RabbitMQ directories and files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rabbitmq
        - /var/lib/rabbitmq
        - /var/log/rabbitmq
        - /usr/lib/rabbitmq
        - /usr/share/rabbitmq
        - /var/run/rabbitmq
        - /etc/systemd/system/rabbitmq-exporter.service

    # 删除 RabbitMQ 用户和组
    - name: Remove RabbitMQ user and group
      user:
        name: rabbitmq
        state: absent
        remove: yes
      ignore_errors: yes

    # 清理 systemd
    - name: Clean systemd
      command: systemctl daemon-reload

    # 清理日志
    - name: Clean RabbitMQ logs
      command: journalctl --vacuum-time=1s --unit=rabbitmq-server
      ignore_errors: yes

    - name: Clean RabbitMQ Exporter logs
      command: journalctl --vacuum-time=1s --unit=rabbitmq-exporter
      ignore_errors: yes 