---
- hosts: all
  become: yes
  tasks:
    - name: Stop RabbitMQ services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - rabbitmq-server
        - rabbitmq-exporter
      ignore_errors: yes

    - name: Remove RabbitMQ and Erlang packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
        autoremove: yes
      with_items:
        - erlang*
        - erlang-base
        - erlang-crypto
        - erlang-eldap
        - erlang-inets
        - erlang-mnesia
        - erlang-os-mon
        - erlang-parsetools
        - erlang-public-key
        - erlang-runtime-tools
        - erlang-ssl
        - erlang-syntax-tools
        - erlang-tools
        - erlang-xmerl
        - rabbitmq-server

    - name: Remove RabbitMQ configuration
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rabbitmq
        - /var/lib/rabbitmq
        - /var/log/rabbitmq

    - name: Remove RabbitMQ repositories and keys
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/sources.list.d/rabbitmq.list
        - /etc/apt/sources.list.d/rabbitmq-erlang.list
        - /usr/share/keyrings/rabbitmq-archive-keyring.gpg
        - /usr/share/keyrings/rabbitmq-erlang-archive-keyring.gpg

    - name: Update apt cache
      apt:
        update_cache: yes

    # 清理 systemd
    - name: Clean systemd
      command: systemctl daemon-reload

    # 清理日志
    - name: Clean RabbitMQ logs
      command: journalctl --vacuum-time=1s --unit=rabbitmq-server
      ignore_errors: yes

    - name: Clean RabbitMQ Exporter logs
      command: journalctl --vacuum-time=1s --unit=rabbitmq-exporter
      ignore_errors: yes 