---
- hosts: all
  become: yes
  tasks:
    - name: Stop PHP-FPM services
      service:
        name: "php{{ item }}-fpm"
        state: stopped
        enabled: no
      loop:
        - "8.1"
        - "8.2"
        - "8.3"
        - "8.4"
      ignore_errors: yes

    - name: Remove PHP packages and dependencies
      apt:
        name: 
          - "php*"
          - "libapache2-mod-php*"
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove PHP configuration directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/php"
        - "/var/log/php"
        - "/var/lib/php"

    - name: Remove PHP repository (Debian)
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        state: absent
        filename: php
      when: ansible_distribution == 'Debian'

    - name: Remove PHP repository key (Debian)
      apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: absent
      when: ansible_distribution == 'Debian'

    - name: Remove Ondrej PPA (Ubuntu)
      apt_repository:
        repo: ppa:ondrej/php
        state: absent
      when: ansible_distribution == 'Ubuntu'

    - name: Update apt cache
      apt:
        update_cache: yes 