---
- hosts: all
  become: yes
  tasks:
    # 停止并禁用所有监控服务
    - name: Stop and disable monitoring services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - prometheus
        - alertmanager
        - grafana-server
        - node_exporter
        - mysql_exporter
        - php-fpm-exporter
        - nginx-exporter
      ignore_errors: yes

    # 删除监控软件包
    - name: Remove monitoring packages
      apt:
        name: 
          - prometheus
          - prometheus-alertmanager
          - grafana
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes

    # 清理配置目录
    - name: Remove configuration directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/prometheus
        - /etc/alertmanager
        - /etc/grafana
        - /var/lib/prometheus
        - /var/lib/grafana
        - /var/lib/alertmanager
        - /usr/local/bin/node_exporter
        - /usr/local/bin/mysql_exporter
        - /usr/local/bin/php-fpm-exporter
        - /usr/local/bin/nginx-exporter

    # 清理日志目录
    - name: Remove log directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/log/prometheus
        - /var/log/alertmanager
        - /var/log/grafana

    # 清理 systemd 服务文件
    - name: Remove systemd service files
      file:
        path: "/etc/systemd/system/{{ item }}"
        state: absent
      with_items:
        - prometheus.service
        - alertmanager.service
        - grafana-server.service
        - node_exporter.service
        - mysql_exporter.service
        - php-fpm-exporter.service
        - nginx-exporter.service

    # 重新加载 systemd
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    # 清理用户和组
    - name: Remove monitoring users and groups
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      with_items:
        - prometheus
        - grafana
        - node_exporter
        - mysql_exporter
        - php-fpm-exporter
        - nginx-exporter
      ignore_errors: yes

    # 清理 APT 源
    - name: Remove Grafana APT repository
      file:
        path: /etc/apt/sources.list.d/grafana.list
        state: absent

    # 更新 APT 缓存
    - name: Update APT cache
      apt:
        update_cache: yes 