---
- hosts: all
  become: yes
  tasks:
    # 停止服务
    - name: Stop monitoring services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - grafana-server
        - prometheus
        - alertmanager
        - node_exporter
        - nginx-exporter
        - php-fpm-exporter
      ignore_errors: yes

    # 删除 Grafana
    - name: Remove Grafana
      apt:
        name: grafana
        state: absent
        purge: yes
      ignore_errors: yes

    # 删除 Grafana 仓库
    - name: Remove Grafana repository
      apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: absent
        filename: grafana

    # 删除 Grafana GPG key
    - name: Remove Grafana GPG key
      apt_key:
        url: https://apt.grafana.com/gpg.key
        state: absent

    # 删除监控组件目录
    - name: Remove monitoring directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/prometheus
        - /var/lib/prometheus
        - /etc/alertmanager
        - /var/lib/grafana
        - /etc/grafana
        - /var/log/grafana
        - /usr/local/bin/prometheus
        - /usr/local/bin/alertmanager
        - /usr/local/bin/node_exporter
        - /usr/local/bin/nginx-exporter
        - /usr/local/bin/php-fpm-exporter

    # 删除 systemd 服务文件
    - name: Remove systemd service files
      file:
        path: "/etc/systemd/system/{{ item }}"
        state: absent
      loop:
        - prometheus.service
        - alertmanager.service
        - node_exporter.service
        - nginx-exporter.service
        - php-fpm-exporter.service

    # 重新加载 systemd
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    # 更新 apt 缓存
    - name: Update apt cache
      apt:
        update_cache: yes 