---
# 安装基础依赖
- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
      - python3-apt
    state: present
    update_cache: yes

# 更新包缓存
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

# 检查可用的 RabbitMQ 版本
- name: Check available RabbitMQ versions
  shell: apt-cache madison rabbitmq-server
  register: rabbitmq_versions
  changed_when: false

- name: Display available RabbitMQ versions
  debug:
    var: rabbitmq_versions.stdout_lines

# 下载 RabbitMQ 签名密钥
- name: Download RabbitMQ signing key
  get_url:
    url: "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA"
    dest: /tmp/rabbitmq-release-signing-key.asc
    mode: '0644'

# 验证密钥指纹
- name: Verify signing key fingerprint
  shell: gpg --with-fingerprint /tmp/rabbitmq-release-signing-key.asc | grep -q "0A9A F211 5F46 87BD 2980  3A20 6B73 A36E 6026 DFCA"
  register: key_verify
  changed_when: false

# 导入 RabbitMQ 签名密钥
- name: Import RabbitMQ signing key
  command: gpg --import /tmp/rabbitmq-release-signing-key.asc
  register: gpg_import
  changed_when: "'imported' in gpg_import.stderr"
  when: key_verify.rc == 0

# 下载 RabbitMQ 服务器包
- name: Download RabbitMQ server package
  get_url:
    url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.7/rabbitmq-server_3.13.7-1_all.deb"
    dest: /tmp/rabbitmq-server.deb
    mode: '0644'

# 下载 RabbitMQ 签名文件
- name: Download RabbitMQ signature
  get_url:
    url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.7/rabbitmq-server_3.13.7-1_all.deb.asc"
    dest: /tmp/rabbitmq-server.deb.asc
    mode: '0644'

# 验证 RabbitMQ 包签名
- name: Verify RabbitMQ package signature
  command: gpg --verify /tmp/rabbitmq-server.deb.asc /tmp/rabbitmq-server.deb
  register: gpg_verify
  failed_when: "'BAD signature' in gpg_verify.stderr"
  changed_when: false

# 安装 RabbitMQ 服务器
- name: Install RabbitMQ server
  apt:
    deb: /tmp/rabbitmq-server.deb
    state: present
  when: "'Good signature' in gpg_verify.stderr"

# 清理下载的文件
- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/rabbitmq-release-signing-key.asc
    - /tmp/rabbitmq-server.deb
    - /tmp/rabbitmq-server.deb.asc

# 启用管理插件
- name: Enable RabbitMQ management plugin
  command: rabbitmq-plugins enable rabbitmq_management
  notify: restart rabbitmq-server

- name: Enable RabbitMQ prometheus plugin
  command: rabbitmq-plugins enable rabbitmq_prometheus
  notify: restart rabbitmq-server

# 确保 RabbitMQ 已启动并启用
- name: Ensure RabbitMQ is started and enabled
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
    daemon_reload: yes

# 配置 RabbitMQ
- name: Create RabbitMQ configuration directory
  file:
    path: /etc/rabbitmq
    state: directory
    mode: '0755'
    owner: rabbitmq
    group: rabbitmq

- name: Configure RabbitMQ
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    mode: '0644'
    owner: rabbitmq
    group: rabbitmq
  notify: restart rabbitmq

- name: Configure RabbitMQ environment
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: '0644'
    owner: rabbitmq
    group: rabbitmq
  notify: restart rabbitmq

# 等待 RabbitMQ 完全启动
- name: Wait for RabbitMQ to be ready
  wait_for:
    port: "{{ rabbitmq_management_port }}"
    delay: 10
    timeout: 300

# 创建管理员用户
- name: Create admin user
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

# 删除默认 guest 用户
- name: Remove default guest user
  rabbitmq_user:
    user: guest
    state: absent

# 配置 RabbitMQ Exporter 服务
- name: Configure RabbitMQ Exporter service
  template:
    src: rabbitmq-exporter.service.j2
    dest: /etc/systemd/system/rabbitmq-exporter.service
    mode: '0644'
  notify: restart rabbitmq-exporter

# 启动并启用服务
- name: Start and enable RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
    daemon_reload: yes

- name: Start and enable RabbitMQ Exporter service
  systemd:
    name: rabbitmq-exporter
    state: started
    enabled: yes
    daemon_reload: yes

# 配置 Prometheus 告警规则
- name: Configure RabbitMQ Prometheus alert rules
  template:
    src: rabbitmq.rules.yml.j2
    dest: /etc/prometheus/rabbitmq.rules.yml
    mode: '0644'
  notify: reload prometheus 