---
# 安装基础依赖
- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
      - debian-keyring
      - debian-archive-keyring
    state: present

# 创建 keyrings 目录
- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# 添加 RabbitMQ 团队的 Erlang 仓库
# 注意：Debian 12 默认仓库的 RabbitMQ 版本是 3.10.x
# 为了安装最新的 3.13.x 版本，我们需要添加官方仓库
- name: Download Team RabbitMQ's Erlang package
  get_url:
    url: https://github.com/rabbitmq/erlang-debian-package/releases/download/v26.0.2/erlang_26.0.2-1_arm64.deb
    dest: /tmp/erlang.deb
    mode: '0644'

# 移除旧版本的 Erlang
- name: Remove old Erlang packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoremove: yes
  with_items:
    - erlang*
    - esl-erlang

# 安装 Erlang
- name: Install Erlang package
  apt:
    deb: /tmp/erlang.deb
    state: present
    force: yes

# 下载 RabbitMQ
- name: Download RabbitMQ package
  get_url:
    url: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.0/rabbitmq-server_3.13.0-1_all.deb
    dest: /tmp/rabbitmq-server.deb
    mode: '0644'

# 安装 RabbitMQ
- name: Install RabbitMQ package
  apt:
    deb: /tmp/rabbitmq-server.deb
    state: present

# 添加 RabbitMQ 仓库密钥
- name: Add RabbitMQ repository key
  shell: |
    curl -1sLf "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key" | gpg --dearmor > /etc/apt/keyrings/rabbitmq.gpg
    chmod 644 /etc/apt/keyrings/rabbitmq.gpg
  args:
    creates: /etc/apt/keyrings/rabbitmq.gpg

# 添加 RabbitMQ 仓库
- name: Add RabbitMQ repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/rabbitmq.gpg arch=arm64] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/debian {{ ansible_distribution_release }} main"
    state: present
    filename: rabbitmq
    update_cache: yes

# 启用管理插件
- name: Enable RabbitMQ plugins
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify: restart rabbitmq-server

# 确保 RabbitMQ 已启动并启用
- name: Ensure RabbitMQ is started and enabled
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

# 配置 RabbitMQ
- name: Create RabbitMQ configuration directory
  file:
    path: /etc/rabbitmq
    state: directory
    mode: '0755'

- name: Configure RabbitMQ
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    mode: '0644'
  notify: restart rabbitmq

- name: Configure RabbitMQ environment
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: '0644'
  notify: restart rabbitmq

# 创建管理员用户
- name: Create admin user
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

# 删除默认 guest 用户
- name: Remove default guest user
  rabbitmq_user:
    user: guest
    state: absent

# 配置 RabbitMQ Exporter 服务
- name: Configure RabbitMQ Exporter service
  template:
    src: rabbitmq-exporter.service.j2
    dest: /etc/systemd/system/rabbitmq-exporter.service
    mode: '0644'
  notify: restart rabbitmq-exporter

# 启动并启用服务
- name: Start and enable RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
    daemon_reload: yes

- name: Start and enable RabbitMQ Exporter service
  systemd:
    name: rabbitmq-exporter
    state: started
    enabled: yes
    daemon_reload: yes

# 配置 Prometheus 告警规则
- name: Configure RabbitMQ Prometheus alert rules
  template:
    src: rabbitmq.rules.yml.j2
    dest: /etc/prometheus/rabbitmq.rules.yml
    mode: '0644'
  notify: reload prometheus 