---
# 安装基础依赖
- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes

# 添加 Team RabbitMQ PPA 密钥
- name: Add Team RabbitMQ PPA key
  apt_key:
    id: F77F1EDA57EBB1CC
    keyserver: keyserver.ubuntu.com
    state: present

# 添加 Team RabbitMQ 的 Erlang 仓库
- name: Add Team RabbitMQ Erlang repository
  apt_repository:
    repo: "ppa:rabbitmq/rabbitmq-erlang"
    state: present
    filename: rabbitmq-erlang

# 更新包缓存
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

# 安装 Erlang
- name: Install Erlang
  apt:
    name: erlang
    state: present
    update_cache: yes

# 检查 Erlang 版本
- name: Check Erlang version
  command: erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
  register: erlang_version
  changed_when: false

- name: Display Erlang version
  debug:
    var: erlang_version.stdout_lines

# 下载和安装 RabbitMQ
- name: Download RabbitMQ signing key
  get_url:
    url: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc"
    dest: /tmp/rabbitmq-release-signing-key.asc
    mode: '0644'

- name: Import RabbitMQ signing key
  command: gpg --import /tmp/rabbitmq-release-signing-key.asc
  register: gpg_import
  changed_when: "'imported' in gpg_import.stderr"

- name: Download RabbitMQ server package
  get_url:
    url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.13.7/rabbitmq-server_3.13.7-1_all.deb"
    dest: /tmp/rabbitmq-server.deb
    mode: '0644'

- name: Install RabbitMQ server
  apt:
    deb: /tmp/rabbitmq-server.deb
    state: present

# 清理下载的文件
- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/rabbitmq-release-signing-key.asc
    - /tmp/rabbitmq-server.deb

# 启用管理插件
- name: Enable RabbitMQ management plugin
  command: rabbitmq-plugins enable rabbitmq_management
  notify: restart rabbitmq-server

# 配置 RabbitMQ
- name: Create RabbitMQ configuration directory
  file:
    path: /etc/rabbitmq
    state: directory
    mode: '0755'
    owner: rabbitmq
    group: rabbitmq

- name: Configure RabbitMQ
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    mode: '0644'
    owner: rabbitmq
    group: rabbitmq
  notify: restart rabbitmq-server

- name: Configure RabbitMQ environment
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: '0644'
    owner: rabbitmq
    group: rabbitmq
  notify: restart rabbitmq-server

# 确保 RabbitMQ 已启动
- name: Ensure RabbitMQ is started and enabled
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
    daemon_reload: yes

# 等待 RabbitMQ 启动完成
- name: Wait for RabbitMQ to be ready
  wait_for:
    port: 5672
    delay: 10
    timeout: 300

# 创建管理员用户
- name: Create admin user
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator
    vhost: /
    configure_priv: ".*"
    read_priv: ".*"
    write_priv: ".*"
    state: present

# 删除默认 guest 用户
- name: Remove default guest user
  rabbitmq_user:
    user: guest
    state: absent 