---
# 安装基础依赖
- name: Install required packages
  apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present

# 创建 keyrings 目录
- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

# 下载 Team RabbitMQ 的密钥
- name: Download RabbitMQ signing key
  get_url:
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA
    dest: /etc/apt/keyrings/rabbitmq.asc
    mode: '0644'

# 导入 Team RabbitMQ 的密钥
- name: Import RabbitMQ signing key
  shell: gpg --dearmor < /etc/apt/keyrings/rabbitmq.asc > /etc/apt/keyrings/rabbitmq.gpg

# 下载 RabbitMQ Erlang 仓库密钥
- name: Download Erlang signing key
  get_url:
    url: https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key
    dest: /etc/apt/keyrings/rabbitmq-erlang.asc
    mode: '0644'

# 导入 RabbitMQ Erlang 仓库密钥
- name: Import Erlang signing key
  shell: gpg --dearmor < /etc/apt/keyrings/rabbitmq-erlang.asc > /etc/apt/keyrings/rabbitmq-erlang.gpg

# 配置 RabbitMQ 仓库
- name: Add RabbitMQ and Erlang repository
  template:
    src: rabbitmq.list.j2
    dest: /etc/apt/sources.list.d/rabbitmq.list
    mode: '0644'

# 更新包索引
- name: Update package indices
  apt:
    update_cache: yes

# 安装 Erlang 包
- name: Install Erlang packages
  apt:
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-public-key
      - erlang-ssl
      - erlang-mnesia
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-os-mon
      - erlang-parsetools
      - erlang-inets
      - erlang-tools
      - erlang-eldap
      - erlang-xmerl
    state: present

# 安装 RabbitMQ
- name: Install RabbitMQ
  apt:
    name: rabbitmq-server={{ rabbitmq_version }}-1
    state: present

# 启用管理插件
- name: Enable RabbitMQ plugins
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify: restart rabbitmq-server

# 确保 RabbitMQ 已启动并启用
- name: Ensure RabbitMQ is started and enabled
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

# 配置 RabbitMQ
- name: Create RabbitMQ configuration directory
  file:
    path: /etc/rabbitmq
    state: directory
    mode: '0755'

- name: Configure RabbitMQ
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    mode: '0644'
  notify: restart rabbitmq

- name: Configure RabbitMQ environment
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: '0644'
  notify: restart rabbitmq

# 创建管理员用户
- name: Create admin user
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

# 删除默认 guest 用户
- name: Remove default guest user
  rabbitmq_user:
    user: guest
    state: absent

# 安装 RabbitMQ Exporter
- name: Download RabbitMQ Exporter
  get_url:
    url: "https://github.com/rabbitmq/rabbitmq-server/releases/download/v{{ rabbitmq_version }}/rabbitmq-server_{{ rabbitmq_version }}-1_all.deb"
    dest: /tmp/rabbitmq-exporter.deb
    mode: '0644'

- name: Install RabbitMQ Exporter
  apt:
    deb: /tmp/rabbitmq-exporter.deb
    state: present

# 配置 RabbitMQ Exporter 服务
- name: Configure RabbitMQ Exporter service
  template:
    src: rabbitmq-exporter.service.j2
    dest: /etc/systemd/system/rabbitmq-exporter.service
    mode: '0644'
  notify: restart rabbitmq-exporter

# 启动并启用服务
- name: Start and enable RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
    daemon_reload: yes

- name: Start and enable RabbitMQ Exporter service
  systemd:
    name: rabbitmq-exporter
    state: started
    enabled: yes
    daemon_reload: yes

# 配置 Prometheus 告警规则
- name: Configure RabbitMQ Prometheus alert rules
  template:
    src: rabbitmq.rules.yml.j2
    dest: /etc/prometheus/rabbitmq.rules.yml
    mode: '0644'
  notify: reload prometheus 