---
- name: Create Alertmanager user
  user:
    name: alertmanager
    system: yes
    shell: /sbin/nologin
    home: /var/lib/alertmanager
    create_home: yes

- name: Download Alertmanager
  get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz
    dest: /tmp/alertmanager.tar.gz
    mode: '0644'

- name: Create Alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: alertmanager
    group: alertmanager
    mode: '0755'
  with_items:
    - /etc/alertmanager
    - /var/lib/alertmanager

- name: Extract Alertmanager
  unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy Alertmanager binary
  copy:
    src: "/tmp/alertmanager-0.26.0.linux-amd64/alertmanager"
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes

- name: Configure Alertmanager
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: alertmanager
    group: alertmanager
    mode: '0644'
  notify: restart alertmanager

- name: Create Alertmanager systemd service
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: '0644'
  notify: restart alertmanager

- name: Start and enable Alertmanager
  systemd:
    name: alertmanager
    state: started
    enabled: yes
    daemon_reload: yes 