---
- name: Create node_exporter group
  group:
    name: node_exporter
    state: present

- name: Create node_exporter user
  user:
    name: node_exporter
    group: node_exporter
    shell: /usr/sbin/nologin
    system: yes
    create_home: no

- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /usr/local/bin/node_exporter

- name: Create Node Exporter service
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    mode: '0644'
  notify: restart node_exporter

- name: Ensure Node Exporter service is enabled and started
  service:
    name: node-exporter
    state: started
    enabled: yes 