---
# RabbitMQ 版本
rabbitmq_version: "3.13.7"
erlang_version: "1:26.2.*"

# RabbitMQ 管理端口
rabbitmq_management_port: 15672

# RabbitMQ 管理员账户
rabbitmq_admin_user: admin
rabbitmq_admin_password: admin123  # 建议在生产环境中使用 vault 加密存储

# RabbitMQ 配置
rabbitmq_tcp_port: 5672
rabbitmq_prometheus_port: 15692
rabbitmq_vm_memory_high_watermark: 0.8
rabbitmq_disk_free_limit: "2GB"

# SSL/TLS 配置
rabbitmq_enable_ssl: false
rabbitmq_ssl_port: 5671
rabbitmq_ssl_cert_file: "/etc/rabbitmq/ssl/cert.pem"
rabbitmq_ssl_key_file: "/etc/rabbitmq/ssl/key.pem"
rabbitmq_ssl_ca_file: "/etc/rabbitmq/ssl/ca.pem"

# 监控配置
rabbitmq_enable_monitoring: true
rabbitmq_exporter_version: "1.0.0-RC18"
rabbitmq_exporter_port: 9419
rabbitmq_exporter_user: monitoring
rabbitmq_exporter_password: monitoring123

# 日志配置
rabbitmq_log_level: info
rabbitmq_log_dir: /var/log/rabbitmq

# 集群配置（预留）
rabbitmq_cluster_enabled: false
rabbitmq_erlang_cookie: CHANGEME
rabbitmq_cluster_nodes: []

# RabbitMQ 内存和磁盘限制
rabbitmq_memory_high_watermark: 0.4
rabbitmq_vm_memory_high_watermark_paging_ratio: 0.5
rabbitmq_disk_free_limit: "1GB"

# RabbitMQ TCP 监听选项
rabbitmq_tcp_listen_options:
  backlog: 128
  nodelay: true
  linger:
    on: true
    timeout: 0
  keepalive: true

# RabbitMQ 系统限制
rabbitmq_ulimit_n: 65536
rabbitmq_ulimit_s: 4096

# RabbitMQ Exporter 配置
rabbitmq_exporter_log_level: info

# Prometheus 告警规则
rabbitmq_memory_usage_threshold: 85
rabbitmq_disk_usage_threshold: 85
rabbitmq_queue_messages_threshold: 1000
rabbitmq_unacked_messages_threshold: 1000

# RabbitMQ 端口配置
rabbitmq_port: 5672

# RabbitMQ 日志配置
rabbitmq_log_level: "info"
rabbitmq_log_dir: "/var/log/rabbitmq"

# RabbitMQ TCP 配置
rabbitmq_tcp_backlog: 128
rabbitmq_tcp_nodelay: "true"
rabbitmq_tcp_linger_on: "true"
rabbitmq_tcp_linger_timeout: 0
rabbitmq_tcp_keepalive: "false"

# RabbitMQ 集群配置
rabbitmq_cluster_enabled: false

# RabbitMQ SSL/TLS 配置
rabbitmq_enable_ssl: false
# rabbitmq_ssl_port: 5671
# rabbitmq_ssl_cert_file: "/etc/rabbitmq/ssl/server.crt"
# rabbitmq_ssl_key_file: "/etc/rabbitmq/ssl/server.key"
# rabbitmq_ssl_ca_file: "/etc/rabbitmq/ssl/ca.crt" 