---
- name: restart rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: restarted
    daemon_reload: yes

- name: restart rabbitmq-exporter
  systemd:
    name: rabbitmq-exporter
    state: restarted
    daemon_reload: yes

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded
