---
- name: restart rabbitmq-server
  systemd:
    name: rabbitmq-server
    state: restarted
    daemon_reload: yes
  register: restart_result
  ignore_errors: yes

- name: check restart status
  shell: |
    echo "=== Service Status ==="
    systemctl status rabbitmq-server.service || true
    echo "=== Journalctl Logs ==="
    journalctl -u rabbitmq-server.service -n 50 --no-pager || true
    echo "=== RabbitMQ Logs ==="
    cat /var/log/rabbitmq/rabbit@$(hostname -s).log || true
  when: restart_result is failed
  ignore_errors: yes

- name: restart rabbitmq-exporter
  systemd:
    name: rabbitmq-exporter
    state: restarted
    daemon_reload: yes

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded
