---
- name: Create Prometheus user
  user:
    name: prometheus
    system: yes
    shell: /sbin/nologin
    home: /var/lib/prometheus
    create_home: yes

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.49.1/prometheus-2.49.1.linux-arm64.tar.gz
    dest: /tmp/prometheus.tar.gz
    mode: '0644'

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus
    - /etc/prometheus/rules
    - /etc/prometheus/rules.d
    - /etc/prometheus/files_sd
    - /etc/prometheus/consoles
    - /etc/prometheus/console_libraries

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy Prometheus binary
  copy:
    src: "/tmp/prometheus-2.49.1.linux-arm64/{{ item }}"
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes
  with_items:
    - prometheus
    - promtool

- name: Copy console files
  copy:
    src: "/tmp/prometheus-2.49.1.linux-arm64/{{ item.src }}"
    dest: "/etc/prometheus/{{ item.dest }}"
    owner: prometheus
    group: prometheus
    mode: '0644'
    remote_src: yes
  with_items:
    - { src: 'consoles', dest: '' }
    - { src: 'console_libraries', dest: '' }

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'
  notify: restart prometheus

- name: Create Prometheus systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  notify: restart prometheus

- name: Start and enable Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes 