---
- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes

- name: reload prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes 