---
- name: restart php8.1-fpm
  service:
    name: php8.1-fpm
    state: restarted
    daemon_reload: yes
  when: php_available_versions['8.1'].state == 'present'

- name: restart php8.2-fpm
  systemd:
    name: php8.2-fpm
    state: restarted
    daemon_reload: yes

- name: restart php8.3-fpm
  systemd:
    name: php8.3-fpm
    state: restarted
    daemon_reload: yes

- name: restart php8.4-fpm
  service:
    name: php8.4-fpm
    state: restarted
    daemon_reload: yes
  when: php_available_versions['8.4'].state == 'present'

- name: stop php8.2-fpm
  systemd:
    name: php8.2-fpm
    state: stopped
    enabled: no

- name: stop php8.3-fpm
  systemd:
    name: php8.3-fpm
    state: stopped
    enabled: no 