---
- name: restart php8.1-fpm
  service:
    name: php8.1-fpm
    state: restarted
    daemon_reload: yes

- name: restart php8.2-fpm
  service:
    name: php8.2-fpm
    state: restarted
    daemon_reload: yes

- name: restart php8.3-fpm
  service:
    name: php8.3-fpm
    state: restarted
    daemon_reload: yes

- name: restart php8.4-fpm
  service:
    name: php8.4-fpm
    state: restarted
    daemon_reload: yes 