---
- name: restart php8.1-fpm
  service:
    name: php8.1-fpm
    state: restarted
    daemon_reload: yes
  when: php_available_versions['8.1'].state == 'present'

- name: restart php8.2-fpm
  service:
    name: php8.2-fpm
    state: restarted
    daemon_reload: yes
  when: php_available_versions['8.2'].state == 'present'

- name: restart php8.3-fpm
  service:
    name: php8.3-fpm
    state: restarted
    daemon_reload: yes
  when: php_available_versions['8.3'].state == 'present'

- name: restart php8.4-fpm
  service:
    name: php8.4-fpm
    state: restarted
    daemon_reload: yes
  when: php_available_versions['8.4'].state == 'present' 